"""LP3 S1 round 2: `lp1-node genesis-decode` input limits under an OS memory limit. Python stdlib only.
    python tests/lp3_genesis_cli.py --bin target/debug/lp1-node --m1 ../../development/m1 [--max-version]

Each check runs the real binary as a child process. On Linux and other systems with RLIMIT_AS, the
child gets an address-space limit (default 64 MiB, including the binary's own mappings) and its peak
RSS is read with wait4. Without RLIMIT_AS (Windows), checks that need a limit are reported as
BLOCKED BY PLATFORM, never as passed; checks without a limit still run.

Inputs are generated by this script into a temporary directory, written in chunks as exact bytes
(binary mode): text mode on Windows would turn every \n into \r\n and an explicit \r\n into \r\r\n,
changing the inputs (round-2 Windows portability fix, see development/lp3/s1-genesisspec/
author-r3-windows-ci/README.md). The large
one-line file reproduces the round-1 failure mode (whole-file read, then abort under a limit) with
this script's own sizes; it is not the reviewer's input, which is not available here.
Prints one JSON object; exit 0 only if no check FAILED.
"""

import argparse
import hashlib
import importlib.util
import json
import os
import platform
import signal
import subprocess
import sys
import tempfile
import time
from pathlib import Path

if hasattr(sys, 'set_int_max_str_digits'):
    sys.set_int_max_str_digits(0)

try:
    import resource
    HAVE_RLIMIT = hasattr(resource, 'RLIMIT_AS') and hasattr(os, 'wait4')
except ImportError:
    resource = None
    HAVE_RLIMIT = False

MAX_SPEC_BYTES = 2818474
MIB = 1 << 20


def list_header(n):
    if n < 56:
        return bytes([0xc0 + n])
    lb = n.to_bytes((n.bit_length() + 7) // 8, 'big')
    return bytes([0xf7 + len(lb)]) + lb


def str_item(raw):
    if len(raw) == 1 and raw[0] < 0x80:
        return raw
    if len(raw) < 56:
        return bytes([0x80 + len(raw)]) + raw
    lb = len(raw).to_bytes((len(raw).bit_length() + 7) // 8, 'big')
    return bytes([0xb7 + len(lb)]) + lb + raw


# Runs the binary from a minimal interpreter so that the child's peak RSS (Linux ru_maxrss also counts
# what a forked child inherits before exec) is not inflated by this script's own memory.
HELPER = """
import json, os, resource, sys
lim = int(sys.argv[1]); argv = sys.argv[2:]
pid = os.fork()
if pid == 0:
    if lim:
        resource.setrlimit(resource.RLIMIT_AS, (lim, lim))
    os.execv(argv[0], argv)
_, st, ru = os.wait4(pid, 0)
sys.stdout.write('\\n' + json.dumps({'status': os.waitstatus_to_exitcode(st), 'maxrss': ru.ru_maxrss}) + '\\n')
"""


def run(binary, path, limit, args=None):
    """Returns (exit code or None, signal or None, stdout rows, output text, max RSS KiB or None, seconds)."""
    out = path + '.out'
    argv = [binary] + (args if args is not None else ['genesis-decode', '--in', path, '--out', out])
    t = time.time()
    if HAVE_RLIMIT:
        p = subprocess.run([sys.executable, '-I', '-S', '-c', HELPER, str(limit or 0)] + argv, capture_output=True)
        lines = p.stdout.decode(errors='replace').rstrip('\n').split('\n')
        meta = json.loads(lines[-1])
        status, rss, text = meta['status'], meta['maxrss'], '\n'.join(lines[:-1]) + p.stderr.decode(errors='replace')
    else:
        p = subprocess.run(argv, capture_output=True)
        status, rss, text = p.returncode, None, (p.stdout + p.stderr).decode(errors='replace')
    dt = round(time.time() - t, 2)
    code, sig = (status, None) if status >= 0 else (None, signal.Signals(-status).name)
    rows = []
    if os.path.exists(out):
        with open(out) as f:
            for line in f:
                r = json.loads(line)
                if isinstance(r.get('detail'), str) and len(r['detail']) > 200:
                    r['detailLength'] = len(r['detail'])
                    r['detailSha'] = hashlib.sha256(r['detail'].encode()).hexdigest()
                    r['detail'] = r['detail'][:40] + '...'
                rows.append(r)
        os.remove(out)
    return code, sig, rows, text.strip()[:300], rss, dt


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--bin', required=True)
    ap.add_argument('--m1', required=True)
    ap.add_argument('--limit-mib', type=int, default=64)
    ap.add_argument('--max-version', action='store_true')
    ap.add_argument('--out')
    a = ap.parse_args()
    binary = str(Path(a.bin).resolve())
    m1 = Path(a.m1).resolve()
    doc = json.loads((m1 / 'm1-draft-0.21/vectors/v3-gsv1.json').read_text())

    def leaf(v):
        if isinstance(v, str):
            return bytes.fromhex(v)
        return bytes.fromhex(v['repeat']) * v['count'] if 'repeat' in v else b''.join(leaf(x) for x in v['concat'])
    gsv1 = b''.join(leaf(s) for s in doc['flatSegments'])
    spec = importlib.util.spec_from_file_location('np_cli', str(m1 / 'm1-draft-0.21/tools/netprofile_ref.py'))
    NP = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(NP)
    s = NP.decode_genesis(gsv1)
    cp = {name: ((1 << w) - 1 if hi is None else (5000 if hi == 'gamma' else hi)) for name, w, lo, hi in NP.CP_FIELDS}
    cp['alpha_bp'] = 5000
    s.update({'chainId': 2 ** 64 - 1, 'CP': cp, 'M_0List': [[b'\x10' * 16 + i.to_bytes(4, 'big'), b'\xb1' * 20] for i in range(1, 65536)]})
    max_valid = NP.encode_genesis(s)
    assert len(max_valid) == MAX_SPEC_BYTES

    results = []
    limit = a.limit_mib * MIB
    tmp = tempfile.mkdtemp(prefix='lp3-genesis-cli-')

    def write(name, chunks):
        """Writes exactly these bytes on every platform: str chunks are ASCII, never newline-translated."""
        path = os.path.join(tmp, name)
        with open(path, 'wb') as f:
            for c in chunks:
                f.write(c.encode('ascii') if isinstance(c, str) else c)
        return path

    def check(name, path, lim, expect, needs_limit=True):
        if needs_limit and not HAVE_RLIMIT:
            results.append({'check': name, 'status': 'BLOCKED BY PLATFORM', 'reason': 'RLIMIT_AS / wait4 not available on %s' % platform.system()})
            return
        code, sig, rows, err, rss, dt = run(binary, path, lim if HAVE_RLIMIT else None)
        problems = expect(code, sig, rows, err)
        results.append({'check': name, 'status': 'FAIL' if problems else 'PASS', 'limitMiB': (lim >> 20) if lim and HAVE_RLIMIT else None,
                        'exit': code, 'signal': sig, 'maxRssKiB': rss, 'seconds': dt, 'problems': problems,
                        'rows': rows[:3] if len(rows) <= 3 else rows[:2] + [rows[-1]], 'output': err if problems else ''})

    def expect_rows(want_exit, want):
        """want: list of dicts for rows 0, 1, ... or of (index, dict) pairs; index -1 is the summary row."""
        pairs = [w if isinstance(w, tuple) else (i, w) for i, w in enumerate(want)]

        def f(code, sig, rows, err):
            p = []
            if sig or code != want_exit:
                p.append('exit %s signal %s, want exit %s' % (code, sig, want_exit))
            for i, w in pairs:
                row = rows[i] if -len(rows) <= i < len(rows) else None
                if row is None or any(row.get(k) != v for k, v in w.items()):
                    p.append('row %d: want %s got %s' % (i, w, row))
            return p
        return f

    # 1. Round-1 failure mode: one 96 MiB-byte input (192 MiB of hex) on one line.
    n = 96 * MIB
    big = write('one-line-192MiB.txt', ['bb' + n.to_bytes(4, 'big').hex()] + ['00' * MIB] * 96 + ['\n'])
    line_bytes = 2 * (5 + n)
    for lim_mib in (256, a.limit_mib):
        check('largeOneLine192MiB.limit%dMiB' % lim_mib, big, lim_mib * MIB,
              expect_rows(1, [{'refused': 'inputTooLarge', 'lineBytes': line_bytes, 'maxSpecBytes': MAX_SPEC_BYTES},
                              (-1, {'check': 'genesis-decode', 'inputs': 1, 'refused': 1})]))
    os.remove(big)
    # 2. One byte above the limit, then the largest valid spec, then a decoder rejection.
    over = write('limit-plus-one.txt', [(b'\x01' * (MAX_SPEC_BYTES + 1)).hex(), '\n', max_valid.hex(), '\n', 'c0\n'])
    check('limitPlusOneThenMaxValid', over, limit,
          expect_rows(1, [{'refused': 'inputTooLarge', 'lineBytes': 2 * MAX_SPEC_BYTES + 2},
                          {'ok': True, 'm0': 65535, 'chainId': 2 ** 64 - 1, 'reencodeEqual': True, 'bootable': False},
                          {'code': 'gsCount', 'detail': 'top 0'},
                          (-1, {'check': 'genesis-decode', 'inputs': 3, 'accepted': 1, 'rejected': 1, 'refused': 1})]))
    check('limitPlusOneThenMaxValid.noLimit', over, None,
          expect_rows(1, [{'refused': 'inputTooLarge'}, {'ok': True, 'm0': 65535}, {'code': 'gsCount'}]), needs_limit=False)
    # 3. Largest framing / structure inputs.
    depth, size = 0, 1
    while size + len(list_header(size)) <= MAX_SPEC_BYTES:
        size += len(list_header(size))
        depth += 1
    heads, sz = [], 1
    for _ in range(depth):
        h = list_header(sz)
        sz += len(h)
        heads.append(h)
    deep = b''.join(reversed(heads)) + b'\x80'
    flat = list_header(MAX_SPEC_BYTES - 4) + b'\x01' * (MAX_SPEC_BYTES - 4)
    shapes = write('max-shapes.txt', [deep.hex(), '\n', flat.hex(), '\n'])
    check('maxDeepAndFlat', shapes, limit,
          expect_rows(0, [{'code': 'gsStructure', 'detail': 'top[0]'}, {'code': 'gsStructure', 'detail': 'top[2]'},
                          (-1, {'check': 'genesis-decode', 'inputs': 2, 'rejected': 2, 'refused': 0})]))
    # 4. Many lines: 100000 copies of GSV1 (about 68 MB).
    many = write('gsv1-x100000.txt', [(gsv1.hex() + '\n') * 1000] * 100)
    check('gsv1Times100000', many, limit, expect_rows(0, [{'ok': True}, {'ok': True}, (-1, {'check': 'genesis-decode', 'inputs': 100000, 'accepted': 100000, 'refused': 0})]))
    os.remove(many)
    # 5. Exact gsVersion detail of large values (compared with Python's own decimal).
    for vlen in [256 * 1024] + ([MAX_SPEC_BYTES - 8] if a.max_version else []):
        raw = b'\xff' * vlen
        line = list_header(len(str_item(raw))) + str_item(raw)
        assert len(line) <= MAX_SPEC_BYTES
        want = str(int.from_bytes(raw, 'big'))
        path = write('version-%d.txt' % vlen, [line.hex(), '\n'])
        check('gsVersion%dBytes' % vlen, path, limit,
              expect_rows(0, [{'code': 'gsVersion', 'detailLength': len(want), 'detailSha': hashlib.sha256(want.encode()).hexdigest()}]))
        os.remove(path)
    # 6. Line forms and refusals.
    forms = write('forms.txt', ['0x' + gsv1.hex() + '\r\n', '\n', 'c10a\n', 'zz\n', 'abc\n', gsv1.hex()])
    check('lineForms', forms, None,
          expect_rows(1, [{'ok': True}, {'code': 'L0', 'detail': 'truncated'}, {'code': 'gsVersion', 'detail': '10'}, {'refused': 'hex'}, {'refused': 'hex'}, {'ok': True},
                          (-1, {'check': 'genesis-decode', 'inputs': 6, 'accepted': 2, 'rejected': 2, 'refused': 2})]),
          needs_limit=False)
    # 7. Below the reserved buffers: a clear error, not an abort.
    check('reservationFailure.limit8MiB', forms, 8 * MIB,
          lambda code, sig, rows, err: [] if (code == 2 and sig is None and 'cannot reserve' in err and not rows) else ['exit %s signal %s output %s' % (code, sig, err)])

    baseline = run(binary, os.path.join(tmp, 'none'), None, ['help'])[4] if HAVE_RLIMIT else None

    statuses = {}
    for r in results:
        statuses[r['status']] = statuses.get(r['status'], 0) + 1
    summary = {'check': 'lp3-genesis-cli', 'ok': statuses.get('FAIL', 0) == 0, 'statuses': statuses, 'platform': platform.system(),
               'rlimitAs': HAVE_RLIMIT, 'defaultLimitMiB': a.limit_mib, 'baselineMaxRssKiB': baseline, 'maxSpecBytes': MAX_SPEC_BYTES, 'python': platform.python_version(),
               'results': results}
    text = json.dumps(summary, indent=1)
    print(text)
    if a.out:
        Path(a.out).write_text(text + '\n')
    for f in os.listdir(tmp):
        os.remove(os.path.join(tmp, f))
    os.rmdir(tmp)
    return 0 if summary['ok'] else 1


if __name__ == '__main__':
    sys.exit(main())
